package com.tareasem3

class CampeonesProvider {
    companion object{
        val campeonesList = listOf<CampeonMundial>(
            CampeonMundial(
                "Uruguay",
                "Uruguay",
                "1930",
                ""),
            CampeonMundial(
                "Italia",
                "Italia",
                "1934",
                ""),
            CampeonMundial(
                "Italia",
                "Francia",
                "1938",
                ""),
            CampeonMundial(
                "Uruguay",
                "Brasil",
                "1950",
                ""),
            CampeonMundial(
                "Alemania",
                "Suiza",
                "1954",
                ""),
            CampeonMundial(
                "Brasil",
                "Suecia",
                "1958",
                ""),
            CampeonMundial(
                "Brasil",
                "Chile",
                "1962",
                ""),
            CampeonMundial(
                "Inglaterra",
                "Inglaterra",
                "1966",
                ""),
            CampeonMundial(
                "Brasil",
                "Mexico",
                "1970",
                ""),
            CampeonMundial(
                "Alemania",
                "Alemania",
                "1974",
                ""),
            CampeonMundial(
                "Argentina",
                "Argentina",
                "1978",
                ""),
            CampeonMundial(
                "Italia",
                "España",
                "1982",
                ""),
            CampeonMundial(
                "Argentia",
                "Mexico",
                "1986",
                ""),
            CampeonMundial(
                "Alemania",
                "Italia",
                "1990",
                ""),
            CampeonMundial(
                "Brasil",
                "USA",
                "1994",
                ""),
            CampeonMundial(
                "Francia",
                "Francia",
                "1998",
                ""),
            CampeonMundial(
                "Brasil",
                "Korea-Japon",
                "2002",
                ""),
            CampeonMundial(
                "Italia",
                "Alemania",
                "2006",
                ""),
            CampeonMundial(
                "España",
                "Sudáfrica",
                "2010",
                ""),
            CampeonMundial(
                "Alemania",
                "Brasil",
                "2014",
                ""),
            CampeonMundial(
                "Francia",
                "Rusia",
                "2018",
                ""),
            CampeonMundial(
                "????",
                "Qatar",
                "2022",
                ""),
        )
    }
}